# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'Online Test' do
  
  use_frameworks!
	
	pod 'IQKeyboardManagerSwift'
	pod 'KRProgressHUD'
	pod 'Alamofire', '~> 4.8'
	pod 'ObjectMapper', '~> 3.5'


  # Pods for Online Test

end
