package com.model.entities;
// Generated Feb 24, 2021, 12:21:22 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.infrashtructure.EntityBase;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Account generated by hbm2java
 */
@Data
@Entity
@EqualsAndHashCode(callSuper = true)
@Table(name = "account", catalog = "quizonline")
public class Account extends EntityBase implements java.io.Serializable {

	private Integer id;
	private Classes classes;
	private String username;
	private String password;
	private String name;
	private Date birthday;
	private boolean status;
	private Date createDate;
	private Set<RoleAccount> roleAccounts = new HashSet<RoleAccount>(0);

	public Account() {
	}

	public Account(Classes classes, String username, String password, String name, Date birthday, boolean status,
			Date createDate) {
		this.classes = classes;
		this.username = username;
		this.password = password;
		this.name = name;
		this.birthday = birthday;
		this.status = status;
		this.createDate = createDate;
	}

	public Account(Classes classes, String username, String password, String name, Date birthday, boolean status,
			Date createDate, Set<RoleAccount> roleAccounts) {
		this.classes = classes;
		this.username = username;
		this.password = password;
		this.name = name;
		this.birthday = birthday;
		this.status = status;
		this.createDate = createDate;
		this.roleAccounts = roleAccounts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "Class_Id", nullable = false)
	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	@Column(name = "Username", nullable = false, length = 250)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "Password", nullable = false, length = 10000)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Birthday", nullable = false, length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "Status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Create_Date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account", cascade = CascadeType.ALL)
	public Set<RoleAccount> getRoleAccounts() {
		return this.roleAccounts;
	}

	public void setRoleAccounts(Set<RoleAccount> roleAccounts) {
		this.roleAccounts = roleAccounts;
	}

}
