package com.model.entities;
// Generated Feb 24, 2021, 12:21:22 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.infrashtructure.EntityBase;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Classes generated by hbm2java
 */
@Data
@Entity
@EqualsAndHashCode(callSuper = true)
@Table(name = "classes", catalog = "quizonline")
public class Classes extends EntityBase implements java.io.Serializable {

	private Integer id;
	private String name;
	private Date createDate;
	private boolean status;
	private Set<Account> accounts = new HashSet<Account>(0);

	public Classes() {
	}

	public Classes(String name, Date createDate, boolean status) {
		this.name = name;
		this.createDate = createDate;
		this.status = status;
	}

	public Classes(String name, Date createDate, boolean status, Set<Account> accounts) {
		this.name = name;
		this.createDate = createDate;
		this.status = status;
		this.accounts = accounts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Create_Date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "Status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classes", cascade = CascadeType.ALL)
	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

}
