package com.model.entities;
// Generated Mar 28, 2021, 10:44:40 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Classes generated by hbm2java
 */
@Entity
@Table(name = "classes", catalog = "quizonline")
public class Classes implements java.io.Serializable {

	private Integer id;
	private Account account;
	private String name;
	private Date createDate;
	private int createBy;
	private int status;
	private Set<ClassesSubject> classesSubjects = new HashSet<ClassesSubject>(0);

	public Classes() {
	}

	public Classes(String name, Date createDate, int createBy, int status) {
		this.name = name;
		this.createDate = createDate;
		this.createBy = createBy;
		this.status = status;
	}

	public Classes(Account account, String name, Date createDate, int createBy, int status,
			Set<ClassesSubject> classesSubjects) {
		this.account = account;
		this.name = name;
		this.createDate = createDate;
		this.createBy = createBy;
		this.status = status;
		this.classesSubjects = classesSubjects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Techer_Id")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "Name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Create_Date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "Create_By", nullable = false)
	public int getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(int createBy) {
		this.createBy = createBy;
	}

	@Column(name = "Status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classes")
	public Set<ClassesSubject> getClassesSubjects() {
		return this.classesSubjects;
	}

	public void setClassesSubjects(Set<ClassesSubject> classesSubjects) {
		this.classesSubjects = classesSubjects;
	}

}
