package com.model.entities;
// Generated Apr 1, 2021, 9:46:29 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExamQuestion generated by hbm2java
 */
@Entity
@Table(name = "exam_question", schema = "dbo", catalog = "quizonline")
public class ExamQuestion implements java.io.Serializable {

	private Integer id;
	private Exam exam;
	private Question question;
	private Date createdDate;
	private int createdBy;
	private int status;
	private Set<StudentAnswer> studentAnswers = new HashSet<StudentAnswer>(0);

	public ExamQuestion() {
	}

	public ExamQuestion(Exam exam, Question question, Date createdDate, int createdBy, int status) {
		this.exam = exam;
		this.question = question;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.status = status;
	}

	public ExamQuestion(Exam exam, Question question, Date createdDate, int createdBy, int status,
			Set<StudentAnswer> studentAnswers) {
		this.exam = exam;
		this.question = question;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.status = status;
		this.studentAnswers = studentAnswers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "exam_Id", nullable = false)
	public Exam getExam() {
		return this.exam;
	}

	public void setExam(Exam exam) {
		this.exam = exam;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_Id", nullable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_Date", nullable = false, length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "created_By", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "examQuestion")
	public Set<StudentAnswer> getStudentAnswers() {
		return this.studentAnswers;
	}

	public void setStudentAnswers(Set<StudentAnswer> studentAnswers) {
		this.studentAnswers = studentAnswers;
	}

}
