package com.model.entities;
// Generated Feb 24, 2021, 12:21:22 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.infrashtructure.EntityBase;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * RoleAccount generated by hbm2java
 */
@Data
@Entity
@EqualsAndHashCode(callSuper = true)
@Table(name = "role_account", catalog = "quizonline")
public class RoleAccount extends EntityBase implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Role role;

	public RoleAccount() {
		
	}

	public RoleAccount(Account account, Role role) {
		this.account = account;
		this.role = role;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "Account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "Role_id", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Override
	public boolean isStatus() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public void setStatus(boolean status) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Date getCreateDate() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setCreateDate(Date createDate) {
		// TODO Auto-generated method stub
		
	}

}
