package com.model.entities;
// Generated Mar 28, 2021, 10:44:40 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.infrashtructure.EntityBase;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Subject generated by hbm2java
 */
@Data
@Entity
@EqualsAndHashCode(callSuper = true)
@Table(name = "subject", catalog = "quizonline")
public class Subject extends EntityBase implements java.io.Serializable {

	private Integer id;
	private String name;
	private Date createDate;
	private int createBy;
	private int status;
	private Set<ClassesSubject> classesSubjects = new HashSet<ClassesSubject>(0);

	public Subject() {
	}

	public Subject(String name, Date createDate, int createBy, int status) {
		this.name = name;
		this.createDate = createDate;
		this.createBy = createBy;
		this.status = status;
	}

	public Subject(String name, Date createDate, int createBy, int status, Set<ClassesSubject> classesSubjects) {
		this.name = name;
		this.createDate = createDate;
		this.createBy = createBy;
		this.status = status;
		this.classesSubjects = classesSubjects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Create_Date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "Create_By", nullable = false)
	public int getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(int createBy) {
		this.createBy = createBy;
	}

	@Column(name = "Status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subject")
	public Set<ClassesSubject> getClassesSubjects() {
		return this.classesSubjects;
	}

	public void setClassesSubjects(Set<ClassesSubject> classesSubjects) {
		this.classesSubjects = classesSubjects;
	}

}
